name: .NET
# このワークフローを実行するタイミングを書く
on:
  # これであればmasterブランチにpushされた時
  push:
    branches: [ master ]
  # こちらはプルリクエストが作られた時
  pull_request:
    branches: [ master ]

# 実行する内容
jobs:
  build:
    # ubuntuの最新バージョンで動かす。
    runs-on: ubuntu-latest

    steps:
    # チェック仮想環境にリポジトリをチェックアウトする
    - uses: actions/checkout@v2
    # .Netのセットアップをする
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup NuGet
      # run: dotnet restore --source https://nuget.pkg.github.com/Tanaka-Electric/index.json
      run: dotnet nuget add source --username TakumiP-Serikawa --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name Telc.BasicExtension "https://nuget.pkg.github.com/Tanaka-Electric/index.json"
    - name: Restore NuGet
      run: dotnet restore
    # ビルド実行
    - name: Build
      run: dotnet build --no-restore
    # テスト実行
    - name: Test
      run: dotnet test --no-build --verbosity normal
