name: .NET

# このワークフローを実行するタイミングを書く
on:
  # これであればmasterブランチにpushされた時
  push:
    branches: [ master ]
  # こちらはプルリクエストが作られた時
  pull_request:
    branches: [ master ]
env:
  GitHubUserName: TakumiP-Serikawa
  NuGetSourceUrl: https://api.nuget.org/v3/index.json
  TelcSourceUrl: https://nuget.pkg.github.com/Tanaka-Electric/index.json

# 実行する内容
jobs:
  build:
    # ubuntuの最新バージョンで動かす。
    runs-on: ubuntu-latest

    steps:
    # チェック仮想環境にリポジトリをチェックアウトする
    - uses: actions/checkout@v2
    # .Netのセットアップをする
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    # NuGet.exeのセットアップをする
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
    # NuGetパッケージソースにTelcを追加する
    - name: Add Telc NuGet Package Source
      run: nuget sources Add -Name Telc -source "${{ env.TelcSourceUrl }}" -UserName ${{ env.GitHubUserName }} -Password ${{ secrets.ForAccessPackage }} -storepasswordincleartext 
    # レストア実行
    - name: Restore
      # ソースを指定してレストアする
      run: nuget restore -Source "${{ env.NuGetSourceUrl }};${{ env.TelcSourceUrl }}"
    # ビルド実行
    - name: Build
      run: dotnet build --no-restore
    # テスト実行
    - name: Test
      run: dotnet test --no-build --verbosity normal
